name: projeqta
description: "Programa de relacionamento para especificadores."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-133.0.dev <4.0.0'

dependencies:
  animations: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg_provider: ^0.1.6
  flutter_svg: '^0.23.0+1'
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  intl: ^0.18.1

dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
  
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/font/SF-Pro-Display-Black.ttf
        - asset: assets/font/SF-Pro-Display-Bold.ttf
        - asset: assets/font/SF-Pro-Display-Light.ttf
        - asset: assets/font/SF-Pro-Display-Medium.ttf
        - asset: assets/font/SF-Pro-Display-Regular.ttf
        - asset: assets/font/SF-Pro-Display-Semibold.ttf
        - asset: assets/font/SF-Pro-Display-Thin.ttf
        - asset: assets/font/SF-Pro-Display-Ultralight.ttf

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/Projecta_Android.png"
#   min_sdk_android: 21
