name: flutter_todo_app
description: Um programa para especificadores by Quero Quero
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg_provider: ^0.1.6
  # flutter_svg: ^0.18.0
  # firebase_core: ^2.15.1
  # firebase_messaging: ^14.6.6
  # url_launcher: ^6.1.12
  cupertino_icons: ^1.0.2
  animations: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # flutter_launcher_icons: 0.11.0
  # flutter_app_name: ^0.1.0
  # change_app_package_name: 1.1.0

# flutter_app_name:
#   name: "ProjeQta"

# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
  
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/font/SF-Pro-Display-Black.ttf
        - asset: assets/font/SF-Pro-Display-Bold.ttf
        - asset: assets/font/SF-Pro-Display-Light.ttf
        - asset: assets/font/SF-Pro-Display-Medium.ttf
        - asset: assets/font/SF-Pro-Display-Regular.ttf
        - asset: assets/font/SF-Pro-Display-Semibold.ttf
        - asset: assets/font/SF-Pro-Display-Thin.ttf
        - asset: assets/font/SF-Pro-Display-Ultralight.ttf

  

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/Projecta_Android.png"
#   min_sdk_android: 21