name: projeqta
description: "Programa de relacionamento para especificadores."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-133.0.dev <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg_provider: ^0.1.6
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1

dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - images/a_dot_ham.jpeg

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/Projecta_Android.png"
#   min_sdk_android: 21
